import { h } from '../shared/dom.js';
import { t } from '../shared/i18n.js';
import { KATEX_CSS } from './libs.js';

// Rendered diagrams are cached so re-renders (live reload, editor typing,
// theme switches back and forth) don't redraw unchanged diagrams.
const SVG_CACHE_SIZE = 50;

const MERMAID_FONT = '-apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif';

let katexCss;
function loadKatexCss() {
  katexCss ??= new Promise((resolve) => {
    const link = h('link', { rel: 'stylesheet', href: chrome.runtime.getURL(KATEX_CSS) });
    link.onload = () => resolve(true);
    link.onerror = () => resolve(false);
    document.head.append(link);
  });
  return katexCss;
}

// Renders the math and Mermaid placeholders emitted by markdown.js.
// `loadLib(name)` must resolve to the library's global (window.katex, window.mermaid).
export function createEnhancer(loadLib) {
  const svgCache = new Map();
  let mermaidTheme = null;
  let mermaidRun = 0;
  let idCounter = 0;

  async function renderMath(root) {
    const nodes = root.querySelectorAll('.mdp-math:not(.mdp-done)');
    if (!nodes.length) return;
    const [katex, cssLoaded] = await Promise.all([loadLib('katex'), loadKatexCss()]);
    for (const el of nodes) {
      try {
        katex.render(el.textContent, el, {
          displayMode: el.classList.contains('mdp-math-display'),
          throwOnError: false,
          strict: false,
          // Without KaTeX's stylesheet fall back to native MathML rendering.
          output: cssLoaded ? 'htmlAndMathml' : 'mathml',
        });
      } catch (err) {
        el.classList.add('mdp-error');
        el.title = err?.message ?? String(err);
      }
      el.classList.add('mdp-done');
    }
  }

  async function renderMermaid(root, scheme) {
    const nodes = root.querySelectorAll('.mdp-mermaid');
    if (!nodes.length) return;
    const run = ++mermaidRun;
    const mermaid = await loadLib('mermaid');
    if (scheme !== mermaidTheme) {
      mermaid.initialize({
        startOnLoad: false,
        securityLevel: 'strict',
        suppressErrorRendering: true,
        theme: scheme === 'dark' ? 'dark' : 'default',
        fontFamily: MERMAID_FONT,
      });
      mermaidTheme = scheme;
    }
    for (const el of nodes) {
      if (run !== mermaidRun) return; // superseded by a newer render or theme change
      el.dataset.source ??= el.textContent;
      const key = `${scheme}\n${el.dataset.source}`;
      if (el.dataset.renderedKey === key) continue;
      let svg = svgCache.get(key);
      if (!svg) {
        const id = `mdp-mermaid-${++idCounter}`;
        try {
          ({ svg } = await mermaid.render(id, el.dataset.source));
          svgCache.set(key, svg);
          if (svgCache.size > SVG_CACHE_SIZE) svgCache.delete(svgCache.keys().next().value);
        } catch (err) {
          document.getElementById(`d${id}`)?.remove();
          if (run === mermaidRun) showMermaidError(el, err);
          continue;
        }
        if (run !== mermaidRun) return;
      }
      el.innerHTML = svg; // generated by Mermaid with securityLevel 'strict'
      el.dataset.renderedKey = key;
      el.classList.remove('mdp-error');
    }
  }

  return {
    // Renders everything under root; errors are reported inline, never thrown.
    async run(root, scheme) {
      const results = await Promise.allSettled([renderMath(root), renderMermaid(root, scheme)]);
      for (const result of results) {
        if (result.status === 'rejected') console.warn('[Markdown Preview]', result.reason);
      }
    },
  };
}

function showMermaidError(el, err) {
  const message = String(err?.message ?? err).trim();
  el.classList.add('mdp-error');
  delete el.dataset.renderedKey;
  el.replaceChildren(
    h('div', { class: 'mdp-error-message' }, `${t('mermaidError')}: ${message}`),
    h('pre', { class: 'mdp-mermaid-source' }, el.dataset.source),
  );
}
